# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman
# theme: jekyll-theme-slate
# theme: jekyll-theme-architect
# theme: jekyll-theme-time-machine
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight
theme: jekyll-theme-modernist
# theme: jekyll-theme-tactile
# theme: jekyll-theme-dinky
# theme: jekyll-theme-hacker
# theme: jekyll-theme-primer
github_url: "https://github.com/Uberhub-Mentorias/"
title: Projeto Uber Mentorias
description: Projeto de Curricularização da Extensão 2025

# Configuração para sobrescrever o link do GitHub no tema
github:
  repository_url: "https://github.com/Uberhub-Mentorias/"
